- name: ec2 instance and r53
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    sg_id: "sg-0411021f836b1fbcc"
    zone_id: "Z08060901N40TB60HLP0H"
    domain_name: "nikvi.fun"
    instances:
    - mongodb

  tasks:
  - name: creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}" 
    register: ec2_output

  - name: print the ec2_output
    ansible.module.debug:
      msg: "{{ ec2_output }}"